const WORKS = [
  {
    title: "Figure drawing I",
    medium: "Graphite on paper",
    dimensions: '8.5" × 11"',
    category: "sketches",
    image: "images/figure i.png",
    originalAvailable: true,
    shopifyProductId: "figure-drawing-i-poster",
  },
  {
    title: "Gesture drawing I",
    medium: "Graphite on paper",
    dimensions: '8.5" × 11"',
    category: "sketches",
    image: "images/gesture i.png",
    originalAvailable: true,
    shopifyProductId: "gesture-drawings-i-poster",
  },
  {
    title: "Self-portrait sketch",
    medium: "Oil on canvas panel",
    dimensions: '5" × 7"',
    image: "images/self-portrait.jpg",
    originalAvailable: true,
    shopifyProductId: "", 
  },
    {
    title: "Still life of fish",
    medium: "Oil on canvas panel",
    dimensions: '5" × 7"',
    image: "images/fish.JPG",
    originalAvailable: true,
    shopifyProductId: "", 
  },
    {
    title: "Still life of Two Oranges",
    medium: "Oil on canvas panel",
    dimensions: '5" × 7"',
    image: "images/oranges.JPG",
    originalAvailable: true,
    shopifyProductId: "", 
  },
    {
    title: "We Were Told There Would Be Shooting Stars",
    medium: "Oil on canvas panel",
    dimensions: '5" × 7"',
    image: "images/shooting-stars.JPG",
    originalAvailable: true,
    shopifyProductId: "", 
  },
    {
    title: "Untitled Grisaille i",
    medium: "Oil on canvas panel",
    dimensions: '5" × 7"',
    image: "images/grisaille.JPG",
    originalAvailable: true,
    shopifyProductId: "",
  },
];
