const WORKS = [
  {
    title: "Self-portrait sketch",
    medium: "Oil on canvas panel",
    dimensions: '5" × 7"',
    image: "images/self-portrait.jpg",
    originalAvailable: true,
    shopifyProductId: "", 
  },
    {
    title: "Still life of fish",
    medium: "Oil on canvas panel",
    dimensions: '5" × 7"',
    image: "images/fish.JPG",
    originalAvailable: true,
    shopifyProductId: "", 
  },
    {
    title: "Still life of Two Oranges",
    medium: "Oil on canvas panel",
    dimensions: '5" × 7"',
    image: "images/oranges.JPG",
    originalAvailable: true,
    shopifyProductId: "", 
  },
    {
    title: "We Were Told There Would Be Shooting Stars",
    medium: "Oil on canvas panel",
    dimensions: '5" × 7"',
    image: "images/shooting-stars.JPG",
    originalAvailable: true,
    shopifyProductId: "", 
  },
    {
    title: "Untitled Grisaille i",
    medium: "Oil on canvas panel",
    dimensions: '5" × 7"',
    image: "images/grisaille.JPG",
    originalAvailable: true,
    shopifyProductId: "", 
  },
    {
    title: "From the corner table at Caffe Reggio",
    medium: "Black & white film",
    dimensions: '35mm',
    category: "photography",
    image: "images/corner table.PNG",
    originalAvailable: true,
    shopifyProductId: "the-corner-table-print", 
  },
  
];
